
export const defaultKinks = [
        { label: "Spanking", variants: ["Playful", "Harsh"] },
        { label: "Spit", variants: [] },
        { label: "Slapping", variants: [] },
        { label: "Ownership", variants: ["Being kept as property/owned"] },
        { label: "Breeding", variants: [] },
        { label: "Rope Bunny", variants: ["Shibari"] },
        { label: "Wax play", variants: [] },
        { label: "Affectionate", variants: ["Cruelty"] },
        { label: "Orgasm denial", variants: ["Orgasm control", "Chastity"] },
        { label: "Edging", variants: [] },
        { label: "Ordered to masturbate", variants: [] },
        { label: "Punishment", variants: ["Punishment", "Real"] },
        { label: "Manhandling", variants: [] },
        { label: "Rules", variants: [] },
        { label: "Pain", variants: [] },
        { label: "Bondage", variants: [] },
        { label: "Play", variants: [] },
        { label: "Being a Brat", variants: [] },
        { label: "Obedience", variants: [] },
        { label: "Humiliation", variants: [] },
        { label: "Degradation", variants: [] },
        { label: "Exhibitionism", variants: [] },
        { label: "Somnophilia", variants: ["Sleeping Beauty syndrome"] },
        { label: "Body Worship", variants: [] },
        { label: "Rough sex", variants: [] },
        { label: "Being Babied", variants: [] },
        { label: "Role play", variants: [] },
        { label: "Sadomasochism", variants: [] },
        { label: "Switch", variants: [] },
        { label: "Master", variants: ["Slave"] },
        { label: "Cumslut", variants: [] },
        { label: "Outdoor play", variants: ["Risky places"] },
        { label: "Cumplay", variants: ["Cumflation"] },
        { label: "Primal sex", variants: [] },
        { label: "Impregnation", variants: ["fantasy"] },
        { label: "Pregnancy", variants: ["fantasy"] },
        { label: "Marks & Bruises", variants: [] },
        { label: "Nipple play", variants: [] },
        { label: "Impact play", variants: [] },
        { label: "Home videos", variants: [] },
        { label: "Oral fixation", variants: [] },
        { label: "Corruption", variants: [] },
        { label: "Free use", variants: [] },
        { label: "Authority Figure", variants: [] },
        { label: "Age Gap", variants: [] },
        { label: "Breastfeeding", variants: [] },
        { label: "Breath Play", variants: ["Gags"] },
        { label: "Pet Play", variants: [] },
        { label: "Praise", variants: [] },
        { label: "Predator", variants: ["Prey"] },
        { label: "Facesitting", variants: [] },
        { label: "Facefucking", variants: [] },
        { label: "Latex / Leather", variants: [] },
        { label: "Rimming", variants: [] },
        { label: "Anal", variants: [] },
        { label: "Water Sports", variants: [] },
        { label: "Group Sex", variants: ["MFM", "MMF", "More"] },
        {
          label: "Tentacles",
          variants: ["Monsters", "Oviposition", "Villains"],
        },
        { label: "Feet", variants: ["80+s"] },
        { label: "Size Difference", variants: [] },
        { label: "Over-stimulation", variants: [] },
        { label: "Caging / Confinement", variants: [] },
      ];
